--order-service

create table ORDEN (
CODIGOOD VARCHAR2(25),
NUM_ORDEN VARCHAR2(25)
);

ALTER TABLE ORDEN ADD CONSTRAINT PK_ORDEN PRIMARY KEY (CODIGOOD);

CREATE TABLE ORDEN_DETALLE(
CODIGOORDET VARCHAR2(25),
SKUCODE VARCHAR2(25),
PRECIO NUMBER,
CANTIDAD NUMBER,
CODIGOOD VARCHAR2(25)
);

ALTER TABLE ORDEN_DETALLE ADD CONSTRAINT PK_ORDEN_DETALLE PRIMARY KEY (CODIGOORDET);
ALTER TABLE ORDEN_DETALLE ADD CONSTRAINT FK_ODDE_CODIGOOD FOREIGN KEY (CODIGOOD) REFERENCES ORDEN (CODIGOOD) ENABLE;

-- /////////////////////////////////////////CREACION DE SEQUENCES

CREATE SEQUENCE ORDEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ORDEN_DETALLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;